### ISSUE TITLE
Issue in ulpi_wrapper

### ISSUE THREAD

**Issue by noasic** [ultraembedded/cores#1]
I believe there is a bug in this core. If a register write is interrupted by an RX CMD update, the state machine will wait forever in the STATE_REG until the ulpi_nxt_i is asserted. At least this is what I'm observing in hardware when interfacing with an SMSC USB3300 chip. The first register write (to Function Control) goes well but the second register write (to OTG Control) is interrupted by an RX CMD and the ulpi_wrapper remains stuck in state 3.
![2018-05-21_11-39-07](https://user-images.githubusercontent.com/1455011/40302094-5755cd8c-5cee-11e8-828f-8895527691a2.png)

**Comment by ultraembedded** [comment]
Hi,

I've pushed what I believe to be a fix - tested under simulation but not with real HW yet.

The issue was with handling (UTMI Rev 1.1 - 3.8.3.1);
'If the PHY aborts the RegWrite by asserting dir, the Link must retry the RegWrite when the bus is idle.'

Please let me know if this fixes the issue for you.

**Comment by noasic** [comment]
Hi, thanks for the quick fix. It looks good to me now. I can see that the core is re-trying the RegWrite, and that it returns to state 0 after RegWrite has completed.
